# Generated by Django 2.2.5 on 2019-11-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='schools-input/'),
        ),
    ]
