# Generated by Django 2.2.5 on 2019-11-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20191115_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
