# Generated by Django 2.2.5 on 2019-12-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectsNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.IntegerField(blank=True, null=True)),
                ('structure', models.IntegerField(blank=True, null=True)),
                ('stability', models.IntegerField(blank=True, null=True)),
                ('excitement', models.IntegerField(blank=True, null=True)),
                ('ideal', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectsPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_player', models.IntegerField(blank=True, null=True)),
                ('coachability', models.IntegerField(blank=True, null=True)),
                ('openness', models.IntegerField(blank=True, null=True)),
                ('extroverted', models.IntegerField(blank=True, null=True)),
                ('temperament', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectsValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradition', models.IntegerField(blank=True, null=True)),
                ('stimulation', models.IntegerField(blank=True, null=True)),
                ('helping_others', models.IntegerField(blank=True, null=True)),
                ('achievement', models.IntegerField(blank=True, null=True)),
                ('taking_pleasure_in_life', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
