# Generated by Django 2.2.5 on 2019-12-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personality_insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityInsights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personality_insights.ProspectsNeeds')),
                ('personality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personality_insights.ProspectsPersonality')),
                ('values', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personality_insights.ProspectsValues')),
            ],
        ),
    ]
