# Generated by Django 2.2.5 on 2019-10-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
