# Generated by Django 2.2.5 on 2019-10-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='')),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('fourty_yard_dash', models.FloatField(blank=True, null=True)),
                ('short_shuttle', models.FloatField(blank=True, null=True)),
                ('vertical', models.FloatField(blank=True, null=True)),
                ('hundred_yard_dash', models.FloatField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=250, null=True)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
