# Generated by Django 2.2.5 on 2019-11-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20191029_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='film_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
