# Generated by Django 2.2.5 on 2019-11-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_prospectsneeds_prospectspersonality_prospectsvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityInsights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.ProspectsNeeds')),
                ('personality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.ProspectsPersonality')),
                ('values', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.ProspectsValues')),
            ],
        ),
    ]
