# Generated by Django 2.2.5 on 2019-11-04 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_personalityinsights'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='personality_insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.PersonalityInsights'),
        ),
    ]
