# Generated by Django 2.2.5 on 2019-11-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_player_personality_insight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
