# Generated by Django 2.2.5 on 2019-11-06 09:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_city_state'),
        ('players', '0015_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='')),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('fourty_yard_dash', models.FloatField(blank=True, null=True)),
                ('short_shuttle', models.FloatField(blank=True, null=True)),
                ('vertical', models.FloatField(blank=True, null=True)),
                ('hundred_yard_dash', models.FloatField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=250, null=True)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('film_grade', models.FloatField(blank=True, null=True)),
                ('athleticism', models.FloatField(blank=True, null=True)),
                ('play_making', models.FloatField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('sat', models.FloatField(blank=True, null=True)),
                ('act', models.FloatField(blank=True, null=True)),
                ('avg_transition_time', models.FloatField(blank=True, null=True)),
                ('avg_completion_time', models.FloatField(blank=True, null=True)),
                ('avg_yards_of_seperation', models.FloatField(blank=True, null=True)),
                ('top_speed', models.FloatField(blank=True, null=True)),
                ('time_to_top_speed', models.FloatField(blank=True, null=True)),
                ('explosive_plays_allowed', models.FloatField(blank=True, null=True)),
                ('avg_closing_speed', models.FloatField(blank=True, null=True)),
                ('catch_rate', models.FloatField(blank=True, null=True)),
                ('qb_passer_rating', models.FloatField(blank=True, null=True)),
                ('avg_yards_after_catch_allowed', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.City')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.Classification')),
                ('personality_insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.PersonalityInsights')),
                ('position', models.ManyToManyField(blank=True, related_name='player_positions', to='players.Positions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.PlayerType')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.School')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.State')),
            ],
        ),
    ]
