# Generated by Django 2.2.5 on 2019-11-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='year',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
