# Generated by Django 2.2.5 on 2019-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_auto_20191107_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
