# Generated by Django 2.2.5 on 2019-11-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_positiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.PositionGroup'),
        ),
    ]
