# Generated by Django 2.2.5 on 2019-11-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_school_logo'),
        ('players', '0022_schoolsvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsHardCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commited_on', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.School')),
            ],
        ),
    ]
