# Generated by Django 2.2.5 on 2019-11-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_fbsoffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fbs_offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.FbsOffers'),
        ),
    ]
