# Generated by Django 2.2.5 on 2019-11-19 10:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0026_player_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='Players/'),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('fitfinder_search', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('search_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
