# Generated by Django 2.2.5 on 2019-12-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0031_auto_20191127_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
