# Generated by Django 2.2.5 on 2019-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_auto_20191202_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
