# Generated by Django 2.2.5 on 2019-12-11 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_player_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notes',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
