# Generated by Django 2.2.5 on 2019-12-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0035_auto_20191211_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='athleticism_score_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_closing_speed_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_transition_time_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_yards_of_seperation_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='time_to_top_speed_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='top_speed_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='total_athleticism_score_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
