# Generated by Django 2.2.5 on 2019-12-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0036_auto_20191212_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
