# Generated by Django 2.2.5 on 2019-12-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0037_auto_20191216_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nfl_logo',
            field=models.FileField(blank=True, null=True, upload_to='Players/'),
        ),
    ]
