# Generated by Django 2.2.5 on 2019-12-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0041_positiongroup_detailed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='personality_insight',
        ),
    ]
