# Generated by Django 2.2.5 on 2019-12-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0042_remove_player_personality_insight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalityInsights',
        ),
        migrations.DeleteModel(
            name='ProspectsNeeds',
        ),
        migrations.DeleteModel(
            name='ProspectsPersonality',
        ),
        migrations.DeleteModel(
            name='ProspectsValues',
        ),
    ]
