# Generated by Django 2.2.5 on 2019-12-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0043_auto_20191221_0544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterData',
        ),
    ]
