# Generated by Django 2.2.5 on 2019-12-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personality_insights', '0002_personalityinsights'),
        ('players', '0044_delete_twitterdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='personality_insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personality_insights.PersonalityInsights'),
        ),
    ]
