# Generated by Django 2.2.5 on 2019-12-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_engagement', '0001_initial'),
        ('players', '0045_player_personality_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='social_engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_engagement.SocialEngagement'),
        ),
    ]
