# Generated by Django 2.2.5 on 2019-12-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0046_player_social_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsvisit',
            name='total',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
