# Generated by Django 2.2.5 on 2019-12-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0048_auto_20191224_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='play_making_raw_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
