# Generated by Django 2.2.5 on 2020-01-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0049_player_play_making_raw_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_twitter_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
