# Generated by Django 2.2.5 on 2020-01-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0050_player_last_twitter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='video_highlight',
            field=models.FileField(blank=True, max_length=650, null=True, upload_to='highlighted-videos/'),
        ),
    ]
