# Generated by Django 2.2.5 on 2020-01-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0052_remove_player_video_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='video_highlight',
            field=models.URLField(blank=True, max_length=650, null=True),
        ),
    ]
