# Generated by Django 2.2.5 on 2020-01-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0055_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsvisit',
            name='total_visits',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
