# Generated by Django 2.2.5 on 2020-01-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0059_fbsoffers_decommit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsvisit',
            name='total_visits',
        ),
    ]
