# Generated by Django 2.2.5 on 2020-02-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0062_auto_20200212_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='comments',
        ),
    ]
