# Generated by Django 2.2.5 on 2020-02-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0064_notes_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
