# Generated by Django 2.2.5 on 2020-02-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0065_auto_20200212_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.TextField(),
        ),
    ]
