# Generated by Django 2.2.5 on 2020-03-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0067_fbsschools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbsoffers',
            name='schools',
        ),
    ]
