# Generated by Django 2.2.5 on 2020-03-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_college'),
        ('players', '0068_remove_fbsoffers_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbsoffers',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='new_schools', through='players.FbsSchools', to='address.School'),
        ),
    ]
