# Generated by Django 2.2.5 on 2020-03-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0069_fbsoffers_schools'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbsschools',
            options={'ordering': ('-added_on',)},
        ),
    ]
