# Generated by Django 2.2.5 on 2020-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0070_auto_20200306_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='video_highlight_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
