# Generated by Django 2.2.5 on 2020-05-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0072_positiongroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='position_groups', to='players.PositionGroup'),
        ),
    ]
