# Generated by Django 2.2.5 on 2020-05-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0073_positions_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='web_highlighted_video',
            field=models.FileField(blank=True, null=True, upload_to='player-highlighted-video/'),
        ),
    ]
