# Generated by Django 2.2.5 on 2020-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0075_oldplaymakingvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldplaymakingvalues',
            name='old_avg_closing_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldplaymakingvalues',
            name='old_avg_transition_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldplaymakingvalues',
            name='old_avg_yards_of_seperation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldplaymakingvalues',
            name='old_time_to_top_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldplaymakingvalues',
            name='old_top_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
