# Generated by Django 2.2.5 on 2019-10-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_user', '0002_schoolinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ra_user.SchoolInfo'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
