# Generated by Django 2.2.5 on 2019-12-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_user', '0014_auto_20191214_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myboard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.Player'),
        ),
    ]
