# Generated by Django 2.2.5 on 2019-12-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_user', '0015_auto_20191216_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
