# Generated by Django 2.2.5 on 2019-12-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_college'),
        ('ra_user', '0019_auto_20191223_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.College'),
        ),
    ]
