# Generated by Django 2.2.5 on 2020-01-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_user', '0020_user_college_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offline',
            field=models.BooleanField(default=False),
        ),
    ]
