# Generated by Django 2.2.5 on 2020-02-04 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_type', models.CharField(choices=[('none', None), ('offers', 'offers'), ('visits', 'visits'), ('commit', 'commit'), ('decommit', 'decommit')], default='none', max_length=50)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
