# Generated by Django 2.2.5 on 2020-01-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialengagement',
            name='last_tweet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
